import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";

export async function getServerSideProps(ctx) {
  const categoryId = ctx.params.categoryId;
  const res = await fetch(
    `https://asia-southeast2-sejutacita-app.cloudfunctions.net/fee-assessment-books?categoryId=${categoryId}`
  );
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data: data } };
}

export default function Book(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul style={{ listStyleType: "none" }}>
          {props.data.map((book, i) => (
            <li key={i} style={{ padding: "20px", marginTop: "15px", border: "1px solid #000" }}>
              <h2>{book.title}</h2>
              <p> {book.description} </p>
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
